apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: xxg2buf2k-go 
  janus-idp.io/tekton: xxg2buf2k-go
  backstage.io/kubernetes-id: xxg2buf2k-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: xxg2buf2k-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml